### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by santiagoarredondo**
Pull request from develop

### CODE REVIEW

**Review by santiagoarredondo — COMMENTED** [review]
Not necessary

**Review by alejandrotorres1350 — COMMENTED** [review]
variable direction must change for address

**Review by juandavid9611 — COMMENTED** [review]
Try to let commits with a serious and descriptive message

**Review by alejandrotorres1350 — COMMENTED** [review]
It is necessary to remove those comments

**Pull request merged**
